site_name: Test Wiki!
theme:
  name: material
docs_dir: docs
site_dir: site
markdown_extensions:
  - attr_list
nav:
  - Home: index.md
  - Another Page: "This is not a test.md"
  - Yet Another Page: "This is another test.md"
  - Test:
      - 'testing stuff': "Test/create a link.md"
      - 'original welcom': "Test/Welcome.md"
