site_name: Test Wiki!
theme:
  name: material
  features:
    - toc.integrate
docs_dir: docs
site_dir: site
markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
nav:
  - Home: index.md
  - Another Page: "This is not a test.md"
  - Yet Another Page: "This is another test.md"
  - Test:
      - 'Overview': "Test/index.md"
      - 'testing stuff': "Test/create a link.md"
      - 'original welcom': "Test/Welcome.md"
extra_css:
  - styles/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
